message(STATUS "Configuring project for emscripten build")

set(GAME_BUILD_FOR_WEB ON)

set(GAME_SHELL_FILE "${CMAKE_SOURCE_DIR}/src/runtime_web/index.html")

set(GAME_EMCC_FLAGS "-s USE_SDL=2")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${GAME_EMCC_FLAGS}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${GAME_EMCC_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${GAME_EMCC_FLAGS} --preload-file ${GAME_DATA_PATH}")
set(CMAKE_EXECUTABLE_SUFFIX ".js")